//! Contract tests for the committed core EPUB fixture corpus
//! (`tests/fixtures/epub/core/`).
//!
//! The corpus is generated by `scripts/make-epub-fixtures.py` and validated
//! by `just check-epub-fixtures` (determinism, checksums, manifest, strict
//! size limits). These tests pin the parser-facing contract on every `cargo
//! test` run: valid fixtures parse, malformed fixtures are rejected, and the
//! corpus stays small. Size limits here are coarse emergency brakes; the
//! authoritative budget lives in `tests/fixtures/epub/fixtures.toml`.

use std::fs;
use std::path::{Path, PathBuf};

use tuxbooks_lib::epub::parse_epub;

fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/epub")
}

/// Top-level .epub files of a generation directory (excludes `malformed/`).
fn valid_fixtures(gen: &str) -> Vec<PathBuf> {
    let dir = corpus_root().join("core").join(gen);
    let mut paths: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|_| panic!("core/{gen} directory missing — run `just make-epub-fixtures`"))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("epub"))
        })
        .collect();
    paths.sort();
    paths
}

fn malformed_fixtures(gen: &str) -> Vec<PathBuf> {
    let dir = corpus_root().join("core").join(gen).join("malformed");
    let mut paths: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|_| panic!("core/{gen}/malformed missing — run `just make-epub-fixtures`"))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("epub"))
        })
        .collect();
    paths.sort();
    paths
}

#[test]
fn valid_core_fixtures_parse_for_both_generations() {
    for gen in ["epub2", "epub3"] {
        let fixtures = valid_fixtures(gen);
        assert!(
            fixtures.len() >= 7,
            "core/{gen} should carry the full coverage set (minimal, navigation, \
             content, styling, links, images, i18n), found {}",
            fixtures.len()
        );
        for path in fixtures {
            let book = parse_epub(&path).unwrap_or_else(|err| {
                panic!("core fixture {} must parse, got: {err:?}", path.display())
            });
            assert!(
                !book.metadata.title.is_empty(),
                "{}: parsed title must not be empty",
                path.display()
            );
            assert!(
                !book.spine.is_empty(),
                "{}: parsed spine must not be empty",
                path.display()
            );
        }
    }
}

#[test]
fn malformed_core_fixtures_are_rejected_for_both_generations() {
    for gen in ["epub2", "epub3"] {
        let fixtures = malformed_fixtures(gen);
        assert!(
            fixtures.len() >= 6,
            "core/{gen}/malformed should cover the rejection set, found {}",
            fixtures.len()
        );
        for path in fixtures {
            let result = parse_epub(&path);
            assert!(
                result.is_err(),
                "malformed fixture {} must be rejected, but parsed successfully",
                path.display()
            );
        }
    }
}

#[test]
fn core_corpus_stays_small() {
    let root = corpus_root().join("core");
    let mut total: u64 = 0;
    for entry in walkdir::WalkDir::new(&root) {
        let entry = entry.unwrap();
        if !entry.file_type().is_file() {
            continue;
        }
        let size = entry.metadata().unwrap().len();
        assert!(
            size <= 1024 * 1024,
            "core fixture {} is {size} bytes — a committed EPUB must stay under \
             1 MiB; move large books to the extended/conformance tiers",
            entry.path().display()
        );
        total += size;
    }
    assert!(
        total <= 2 * 1024 * 1024,
        "core corpus totals {total} bytes — the committed EPUB corpus must stay \
         under 2 MiB; move large books to the extended/conformance tiers"
    );
}
