import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { policyFetchClient } from "../../src/lib/epub/contentPolicy";

/**
 * Reader-regression fixtures (generated by scripts/make-epub-fixtures.py,
 * docs/COVERAGE.md EPUB reader lib row). Each source directory mirrors one
 * real-world EPUB shape from the licensed-corpus survey: the toolkit
 * strict-parses every manifest-XHTML item, so whatever the fence emits for
 * these members must re-parse as XML without a parsererror — even though
 * the resource protocol serves .html members as text/html.
 */
const sourcesRoot = path.resolve(__dirname, "../../../tests/fixtures/epub/sources/epub3");

interface FixtureClass {
  dir: string;
  label: string;
  sections: string[];
}

const fixtureClasses: FixtureClass[] = [
  {
    dir: "reader-html-members",
    label: "no XML declaration, .html transport",
    sections: ["section1.html", "section2.html", "section3.html"],
  },
  {
    dir: "reader-mangled-prolog",
    label: "declaration escaped as a comment",
    sections: ["section1.html", "section2.html", "section3.html"],
  },
  {
    dir: "reader-html-entities",
    label: "named entities no XML parser resolves",
    sections: ["symbols.html", "prose.html"],
  },
  {
    dir: "reader-theme-sections",
    label: "no declaration, publisher CSS linked",
    sections: ["part1.html", "part2.html", "part3.html"],
  },
];

function fixtureSource(fixture: string, member: string): string {
  return readFileSync(path.join(sourcesRoot, fixture, "OEBPS", member), "utf-8");
}

describe("the fence re-parses as XML for every real-world member shape", () => {
  for (const { dir, label, sections } of fixtureClasses) {
    for (const member of sections) {
      it(`fences ${dir} (${label}) — ${member}`, async () => {
        const raw = fixtureSource(dir, member);
        const client = policyFetchClient("tuxbooks://book/1/", () =>
          Promise.resolve(
            new Response(raw, { status: 200, headers: { "content-type": "text/html" } }),
          ),
        );
        const text = await (await client(`tuxbooks://book/1/${member}`)).text();
        const reparsed = new DOMParser().parseFromString(text, "application/xhtml+xml");
        const error = reparsed.querySelector("parsererror");
        expect(error?.textContent ?? null, `parsererror for ${member}`).toBeNull();
        // The content survives the fence: the section heading is still there.
        const heading = /<h1>([^<]+)<\/h1>/.exec(raw)?.[1] ?? "";
        expect(heading).not.toBe("");
        expect(reparsed.querySelector("h1")?.textContent ?? "").toContain(heading.slice(0, 12));
      });
    }
  }
});
