import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(here, "../..");

/** Debug binary built by `just build-debug` (embedded assets). */
export const appBinary =
  process.env.E2E_APP_BIN ?? path.join(repoRoot, "src-tauri", "target", "debug", "tuxbooks");

/** Deterministic fixtures generated by `scripts/make-fixture.py`. */
export const epubFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.epub");
export const pdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.pdf");
export const largePdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "large.pdf");
export const mixedPdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "mixed.pdf");

export const seededBookTitles = {
  epub: "A Minimal Book",
  pdf: "A Minimal Manual",
  largePdf: "A Large Fixture",
  mixedPdf: "Odd Sizes",
} as const;

/**
 * Real-book fixtures for the performance benchmark suite only
 * (`just bench-reader`): image-laden pages and heavy EPUB sections make
 * render/turn latency measurement meaningful in a way the synthetic
 * fixtures deliberately are not. Never seeded by the CI phases.
 */
export const benchPdfFixture = path.join(
  repoRoot,
  "tests",
  "fixtures",
  "books",
  "EBooks",
  "Agents",
  "AI_Agents_and_Applications.pdf",
);
export const benchEpubFixture = path.join(
  repoRoot,
  "tests",
  "fixtures",
  "books",
  "EBooks",
  "Agents",
  "AI_Agents_and_Applications.epub",
);

/** Cards expose `aria-label="{title} ({FORMAT})"`; both books share a title. */
export const benchBookTitles = {
  pdf: "AI Agents and Applications (PDF)",
  epub: "AI Agents and Applications (EPUB)",
} as const;
