import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(here, "../..");

/** Debug binary built by `just build-debug` (embedded assets). */
export const appBinary =
  process.env.E2E_APP_BIN ?? path.join(repoRoot, "src-tauri", "target", "debug", "tuxbooks");

/** Deterministic fixtures generated by `scripts/make-fixture.py`. */
export const epubFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.epub");
export const pdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.pdf");

export const seededBookTitles = {
  epub: "A Minimal Book",
  pdf: "A Minimal Manual",
} as const;
