import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(here, "../..");

/** App entry point (CJS bundle built by scripts/build-electron.mjs). */
export const appEntryPoint =
  process.env.E2E_APP_ENTRY ?? path.join(repoRoot, "electron", "dist", "main.cjs");

/**
 * Real (symlink-resolved) Electron dist directory — kill patterns must match
 * the actual command line, and pnpm exposes electron through a symlink. The
 * directory (not the binary) is the sweep scope: the app tree spawns helper
 * processes from the same dist (chrome_crashpad_handler and friends) whose
 * argv never contains "…/dist/electron".
 */
export const electronDistPath = fs.realpathSync(
  path.join(repoRoot, "e2e", "node_modules", "electron", "dist"),
);

/**
 * Rust sidecar binary spawned by the app. Debug build by default; the
 * release flavor (`just test-e2e-release`) overrides via TUXBOOKS_SIDECAR —
 * the packaged-app resource-resolution path exercised ahead of
 * electron-builder packaging (migration phase 5).
 */
export const sidecarBinaryPath =
  process.env.TUXBOOKS_SIDECAR ?? path.join(repoRoot, "src-tauri", "target", "debug", "tuxbooks");

/** Deterministic fixtures generated by `scripts/make-fixture.py`. */
export const epubFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.epub");
export const pdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "minimal.pdf");
export const largePdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "large.pdf");
export const mixedPdfFixture = path.join(repoRoot, "tests", "fixtures", "books", "mixed.pdf");

export const seededBookTitles = {
  epub: "A Minimal Book",
  pdf: "A Minimal Manual",
  largePdf: "A Large Fixture",
  mixedPdf: "Odd Sizes",
} as const;

/**
 * Real-book fixtures for the performance benchmark suite only
 * (`just bench-reader`): image-laden pages and heavy EPUB sections make
 * render/turn latency measurement meaningful in a way the synthetic
 * fixtures deliberately are not. Never seeded by the CI phases.
 */
export const benchPdfFixture = path.join(
  repoRoot,
  "tests",
  "fixtures",
  "books",
  "EBooks",
  "Agents",
  "AI_Agents_and_Applications.pdf",
);
export const benchEpubFixture = path.join(
  repoRoot,
  "tests",
  "fixtures",
  "books",
  "EBooks",
  "Agents",
  "AI_Agents_and_Applications.epub",
);

/** Cards expose `aria-label="{title} ({FORMAT})"`; both books share a title. */
export const benchBookTitles = {
  pdf: "AI Agents and Applications (PDF)",
  epub: "AI Agents and Applications (EPUB)",
} as const;
