import type { Book } from "@/types/domain";

/**
 * A book fixture: identical to the shared payload shape (milestone 10 added
 * the reading-progress fields to `list_books`).
 */
export type FixtureBook = Book;

/**
 * Realistic, original sample data so the UI can be evaluated visually.
 * Dates are staggered to exercise "Recently Added" / "Recently Read" ordering.
 * File-snapshot fields (available/fileSize/fileMtime) get representative
 * defaults below so each fixture reads like a healthy import.
 */
const rawFixtureBooks: Omit<FixtureBook, "available" | "fileSize" | "fileMtime">[] = [
  {
    id: 1,
    path: "/library/the-quiet-meridian.epub",
    publicationDate: "2025-04-14",
    seriesId: 1,
    seriesIndex: 1,
    seriesName: "The Long Coast Quartet",
    format: "epub",
    title: "The Quiet Meridian",
    subtitle: "Notes from the Long Coast",
    author: "Elena Vasquez",
    publisher: "Harborlight Press",
    language: "en",
    isbn: "978-0-00-000001-1",
    description:
      "A season of tide charts, radio static, and the slow repair of a family held together by distance.",
    coverPath: null,
    addedAt: "2026-08-12T09:15:00.000Z",
    modifiedAt: "2026-08-12T09:15:00.000Z",
    lastOpenedAt: "2026-08-28T20:42:00.000Z",
    progressPercent: 78,
    progressUpdatedAt: "2026-08-28T20:42:00.000Z",
  },
  {
    id: 2,
    path: "/library/systems-of-arrangement.pdf",
    publicationDate: "2019-09-02",
    seriesId: null,
    seriesIndex: null,
    seriesName: null,
    format: "pdf",
    title: "Systems of Arrangement",
    subtitle: null,
    author: "Tomas Lindqvist",
    publisher: "Northlight Academic",
    language: "en",
    isbn: "978-0-00-000002-2",
    description:
      "How libraries, herbaria, and archives impose order on abundance without losing the individual object.",
    coverPath: null,
    addedAt: "2026-08-10T14:00:00.000Z",
    modifiedAt: "2026-08-10T14:00:00.000Z",
    lastOpenedAt: null,
    progressPercent: null,
    progressUpdatedAt: null,
  },
  {
    id: 3,
    path: "/library/cartography-of-sleep.epub",
    publicationDate: "2021-11-08",
    seriesId: 1,
    seriesIndex: 2,
    seriesName: "The Long Coast Quartet",
    format: "epub",
    title: "Cartography of Sleep",
    subtitle: null,
    author: "Amara Diallo",
    publisher: "Harborlight Press",
    language: "en",
    isbn: "978-0-00-000003-3",
    description:
      "An atlas of night: dreams recorded across three generations of one migrating family.",
    coverPath: null,
    addedAt: "2026-07-30T18:30:00.000Z",
    modifiedAt: "2026-07-30T18:30:00.000Z",
    lastOpenedAt: "2026-08-27T22:10:00.000Z",
    progressPercent: 12,
    progressUpdatedAt: "2026-08-27T22:10:00.000Z",
  },
  {
    id: 4,
    path: "/library/the-lantern-archive.epub",
    publicationDate: "2018-03-27",
    seriesId: null,
    seriesIndex: null,
    seriesName: null,
    format: "epub",
    title: "The Lantern Archive",
    subtitle: null,
    author: "Hana Sato",
    publisher: "Foxglove & Co.",
    language: "en",
    isbn: "978-0-00-000004-4",
    description:
      "A lighthouse keeper inherits a cellar of unsent letters and answers them, one storm at a time.",
    coverPath: null,
    addedAt: "2026-07-21T11:05:00.000Z",
    modifiedAt: "2026-07-21T11:05:00.000Z",
    lastOpenedAt: "2026-08-25T07:55:00.000Z",
    progressPercent: 100,
    progressUpdatedAt: "2026-08-25T07:55:00.000Z",
  },
  {
    id: 5,
    path: "/library/field-notes-on-silence.pdf",
    publicationDate: "2023-10-03",
    seriesId: null,
    seriesIndex: null,
    seriesName: null,
    format: "pdf",
    title: "Field Notes on Silence",
    subtitle: "Essays on Sound and Absence",
    author: "Petter Moen",
    publisher: "Northlight Academic",
    language: "en",
    isbn: "978-0-00-000005-5",
    description:
      "Nine essays on the places sound abandons: anechoic rooms, empty theatres, off-season resorts.",
    coverPath: null,
    addedAt: "2026-07-15T16:45:00.000Z",
    modifiedAt: "2026-07-15T16:45:00.000Z",
    lastOpenedAt: null,
    progressPercent: null,
    progressUpdatedAt: null,
  },
  {
    id: 6,
    path: "/library/a-grammar-of-rivers.epub",
    publicationDate: "2020-01-21",
    seriesId: null,
    seriesIndex: null,
    seriesName: null,
    format: "epub",
    title: "A Grammar of Rivers",
    subtitle: null,
    author: "Sofia Marchetti",
    publisher: "Foxglove & Co.",
    language: "en",
    isbn: "978-0-00-000006-6",
    description:
      "A hydrologist and a poet trade notebooks for a year, mapping the same watershed in different languages.",
    coverPath: null,
    addedAt: "2026-06-28T08:20:00.000Z",
    modifiedAt: "2026-06-28T08:20:00.000Z",
    lastOpenedAt: null,
    progressPercent: null,
    progressUpdatedAt: null,
  },
  {
    id: 7,
    path: "/library/winter-arithmetic.pdf",
    publicationDate: null,
    seriesId: null,
    seriesIndex: null,
    seriesName: null,
    format: "pdf",
    title: "Winter Arithmetic",
    subtitle: null,
    author: "Jonas Weber",
    publisher: "Small Hours Editions",
    language: "en",
    isbn: "978-0-00-000007-7",
    description:
      "A village accountant tallies what the cold takes and what it leaves behind, in columns that begin to rhyme.",
    coverPath: null,
    addedAt: "2026-06-12T13:10:00.000Z",
    modifiedAt: "2026-06-12T13:10:00.000Z",
    lastOpenedAt: "2026-08-20T19:30:00.000Z",
    progressPercent: 45,
    progressUpdatedAt: "2026-08-20T19:30:00.000Z",
  },
  {
    id: 8,
    path: "/library/the-cartographers-apprentice.epub",
    publicationDate: "2017-05-16",
    seriesId: 2,
    seriesIndex: 1,
    seriesName: "Atlas Cycle",
    format: "epub",
    title: "The Cartographer's Apprentice",
    subtitle: null,
    author: "Priya Raman",
    publisher: "Small Hours Editions",
    language: "en",
    isbn: "978-0-00-000008-8",
    description:
      "Mapped roads keep moving; the apprentice learns that a good map records what the mapmaker refuses to see.",
    coverPath: null,
    addedAt: "2026-05-30T10:00:00.000Z",
    modifiedAt: "2026-05-30T10:00:00.000Z",
    lastOpenedAt: null,
    progressPercent: null,
    progressUpdatedAt: null,
  },
];

export const fixtureBooks: FixtureBook[] = rawFixtureBooks.map((book, index) => ({
  ...book,
  available: true,
  fileSize: 900_000 + index * 137_000,
  fileMtime: 1_760_000_000 + index * 86400,
}));
